const ACCESS_TOKEN_SECRET = "access-token";
const ACCESS_TOKEN_EXPIRY = "1m";
const REFRESH_TOKEN_SECRET = "refreshtoken";
const REFRESH_TOKEN_EXPIRY = "15m";

export {
  ACCESS_TOKEN_EXPIRY,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRY,
  REFRESH_TOKEN_SECRET,
};
