import { Navbar } from "./ui/Header";
import { roboto } from "./lib/fonts";
import "@/app/globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
